### ISSUE TITLE
Results Cannot Be Replicated

### ISSUE THREAD

**Issue by chentong456** [Chokyotager/BIND#1]
I am unable to replicate your sample results using your sample data. I'm looking forward to a resolution. thank you.

**Comment by Chokyotager** [comment]
Hi there, thanks for raising this issue.

1. What is the dataset and corresponding metric that you are unable to replicate?
2. What are the SMILES and FASTA inputs that you are using?

**Comment by Chokyotager** [comment]
Hi chentong456

I found the bug. Apparently, in the local code, we used explicit hydrogens but this was not reflected in the public repository, this led to significant degradation of the results. I have fixed this in `smiles_parser.py`. Can you please try to re-clone starting from commit #83698c6 or use the latest release. Let me know if you can replicate the results now.

Thank you so much for pointing this out!

H

**Comment by chentong456** [comment]
Thank you for your help! Now it works.
